services:
  - type: web
    name: goktilsimi
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: GROQ_API_KEY
        value: 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
      - key: JWT_SECRET
        value: mystical-stars-secret-key-change-in-production-2024
      - key: SMTP_HOST
        value: smtp-relay.brevo.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        value: 9d6f7c001@smtp-brevo.com
      - key: SMTP_PASS
        value: xsmtpsib-f30c6ecef60406f11317c44cc57923eddb268e139802cd031bed60c904921d5d-tsUt0LVYEq2R5NfK
      - key: EMAIL_FROM
        value: GokTilsimi <goktilsimi@gmail.com>
